apiVersion: v1
kind: Service
metadata:
  name: {{.Release.Name}}-redis
  labels:
    project: counter
spec:
  selector:
    project: counter
    app: {{.Release.Name}}-redis
  ports:
    - port: 6379
