apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{.Release.Name}}-redis
  labels:
    project: counter
spec:
  serviceName: redis
  selector:
    matchLabels:
      project: counter
      app: {{.Release.Name}}-redis
  template:
    metadata:
      labels:
        project: counter
        app: {{.Release.Name}}-redis
    spec:
      containers:
        - name: main
          image: redis
          resources:
            requests:
              cpu: 30m
              memory: 50Mi
            limits:
              cpu: 50m
              memory: 80Mi
          ports:
            - containerPort: 6379
